### ISSUE TITLE
Uncaught ReferenceError: module is not defined

### ISSUE THREAD

**Issue by pkpg** [catppuccin/daisyui#39] opened 2024-10-25 08:12 UTC
I try to add the theme to my project and I get:

```
@catppuccin_daisyui.js?v=348caec0:1762 Uncaught ReferenceError: module is not defined
    at @catppuccin_daisyui.js?v=348caec0:1762:1
(anonymous) @ @catppuccin_daisyui.js?v=348caec0:1762

@catppuccin_daisyui.js?v=348caec0:1762 Uncaught (in promise) ReferenceError: module is not defined
    at @catppuccin_daisyui.js?v=348caec0:1762:1
```

**Comment by Liumingxun** [comment] 2024-10-31 02:45
Hi @pkpg, 

To help me better understand your issue, could you provide a minimal reproduction of this problem? It will make it easier for me to investigate and identify a solution.

I’ve put together [a sample project](https://codesandbox.io/p/devbox/7pj46k) with a workable configuration. I hope it’s helpful for you!

**Comment by Liumingxun** [comment] 2024-11-15 08:13
After these past few weeks of my practice, I feel that it may be because you directly imported the file into the browser environment. However, browsers do not have a `module` variable, which causes this error. I've adjusted the build configuration to avoid this issue; but, you still should not directly import this file into the browser.

---

Given that you have not responded for a long time, I have closed this issue. Hopefully, your problem has been resolved.

**Closed by Liumingxun** 2024-11-15 08:13 UTC
